//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiccionarioV2.persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class Palabra
    {
        public Palabra()
        {
            this.Antonimo = new HashSet<Antonimo>();
            this.Sinonimo = new HashSet<Sinonimo>();
        }
    
        public int IdUsuario { get; set; }
        public int IdPalabra { get; set; }
        public string Palabra1 { get; set; }
        public string PrimeraLetra { get; set; }
        public string UltimaLetra { get; set; }
        public Nullable<int> Tamaño { get; set; }
        public Nullable<int> Cant_Vocales { get; set; }
        public Nullable<int> Cant_Consonates { get; set; }
        public string Significado { get; set; }
    
        public virtual ICollection<Antonimo> Antonimo { get; set; }
        public virtual ICollection<Sinonimo> Sinonimo { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
