//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiccionarioV2.persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.Palabra = new HashSet<Palabra>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Nickname { get; set; }
        public string Contraseña { get; set; }
        public string Correo { get; set; }
    
        public virtual ICollection<Palabra> Palabra { get; set; }
    }
}
